### PR TITLE
fix: fix bug where search cannot be done without fully clearing input

### LINKED ISSUE #73: Geocoder requiring input to be cleared before searching for entire set of places after a single result search
Dupe of https://github.com/aws-amplify/amplify-ui/issues/1797

Bug was discovered in the amplify-ui repo which wraps the maplibre-gl-geocoder component

## Please describe your bug.
I'm using the Geocoder component, and I'm seeing an issue where I can't search for another set of places after clicking on a single result from the search result container. The issue does not happen if I clear the input of the search box before performing a search for the set of places so it is a minor bug.

## What's the expected behaviour?
The search box should continue to allow searching for a new set of places, after clicking on a single result, without having to clear the content of the search box.

## Help us reproduce the bug!
Type in "ATM" in the search box and hit "Enter" on the keyboard
The map should display markers for a set of ATMs
Click on the first result from the search result container
The map should display a single marker for the first result's ATM
Highlight the entire text and type in "Grocery Store" (highlighting entire text and overwriting it with "Grocery Store" will prevent it from clearing the input)
Hit "Enter" on the keyboard
Nothing will happen

### PR DESCRIPTION
**Pull request by thaddmt**
### Overview
- Bug discovered where user cannot perform a search without clearing the text box
- Fixes https://github.com/maplibre/maplibre-gl-geocoder/issues/73

 - [x] briefly describe the changes in this PR
 - [x] write tests for all new functionality
 - [x] run `npm run docs` and commit changes to API.md
 - [x] update CHANGELOG.md with changes under `main` heading before merging

### CODE REVIEW

**Review by wipfli — CHANGES_REQUESTED** [review]
Thanks for this pull request @thaddmt Can you add a description of how to reproduce the problematic behavior before this pull request? Maybe in a separate issue bug report...

**Comment by thaddmt** [comment]
@wipfli yes! my bad forgot that the issue was filed in the amplify ui repo - https://github.com/maplibre/maplibre-gl-geocoder/issues/73

**Review by slaymance — APPROVED** [review]
Tested with a react application and this PR fixes the problem!

**Review by wipfli — APPROVED** [review]
Thanks for the updated bug description in the issue, @thaddmt. Was able to reproduce it and this fixes the bug indeed.

**Pull request merged**
