### PR TITLE
Modernize the codebase using typescript typings, rollup, typedoc and jest.

### LINKED ISSUE #21: options.popup defaults to "false", but documented as "true"
The `options.popup` parameter to `MaplibreGeocoder` is defaulted to `false` while the JSDoc definition and reference in `API.md` specify the default value of `options.popup` as `true`.

We can resolve this by either:
- Setting the default value of `options.popup` to `true` ([L87](https://github.com/maplibre/maplibre-gl-geocoder/blob/main/lib/index.js#L87))
- Updating the JSDoc description ([L47](https://github.com/maplibre/maplibre-gl-geocoder/blob/main/lib/index.js#L47)) and the reference in `API.md` ([L99](https://github.com/maplibre/maplibre-gl-geocoder/blob/main/API.md?plain=1#L99)) to a default value of `false`

Updating reference to the default value has the benefit of not impacting users' applications if they upgrade to the version which contains the fix.

### LINKED ISSUE #63: Migrate unit tests from tape to jest
We have migrated all unit tests in MapLibre GL JS from tap/tape to jest. I think it would make sense to do the same here. 

Relevant issue in GL JS: 

https://github.com/maplibre/maplibre-gl-js/issues/273

### LINKED ISSUE #104: Events library dependency
Hi! I had a problem with an app I built that uses maplibre-gl-geocoder. The component wouldn't work because the events library required in index.js is not listed in the dependencies in package.json.

I added the dependency to my project's package.json, and now it works. I'm not sure if I'm doing something wrong, but maybe maplibre-gl-geocoder's package.json should have "events" in its dependencies list?

Thank you for your work on this library, though - it's great!

### LINKED ISSUE #110: Every link to "Carmen GeoJSON" format reference is broken in API.md and in JSDocs in source.
Every instance of [Carmen GeoJSON](https://github.com/mapbox/carmen/blob/master/carmen-geojson.md) in the source code JSDocs and in API.md points to a 404 page on Github. I tried Googling for a definition of Carmen GeoJSON format but came up empty.

The source code example of the getPlaceById function in the geocoderApi parameter contains what I think may be a definition of a Carment GeoJSON feature as used in this project: 
```
{
  type: string, 
  geometry: {
    type: string, 
    coordinates: [number]
  }, 
  place_name: string, 
  text: string, 
  center: [number] 
}[]
```
Am I correct in assuming everything is required except ```text```?
Am I correct in assuming that the first ```type``` always has to be 'Feature' and ```geometry.type``` always has to be 'Point'?

NOTE: API.md incorrectly states that getPlaceById should return an array of text/placeId suggestions.

### LINKED ISSUE #111: add documentation for package dependencies if it is used in vite
I had an error of `TypeError: EventEmitter is not a constructor` when I use it with vite.

I found the below stackoverflow,
https://stackoverflow.com/questions/69717406/typeerror-eventemitter-is-not-a-constructor-at-new-mapboxgeocoder

then, I found the following dependencies are necessary to use this geocoder.

```
npm i -D events @types/events @types/node
```

I am not sure how many people are using vite with this geocoder, but this dependencies info can be documented somewhere in the repo. I think vite is becoming more popular.

### LINKED ISSUE #112: Typescript types
Does this package has typescript types?
Is it possible to add support for typescript?

### PR DESCRIPTION
**Pull request by HarelM**
This is a full migration to typescript, rollup and typedoc.
There's still a need to convert the tests to typescript, and probably jest which I haven't done yet.

Fixes #104 
Fixes #112 
Fixes #111
Fixes #110
Fixes #63
Fixes #21

### CODE REVIEW

**Comment by HarelM** [comment]
@thaddmt @danawoodman This is now ready for review.
I've done a lot of changes as part of this PR to modernize this library.
Test are still lagging behind due to a lot of orchestration that needs to be done in order to run tests in the browser.
`sinon` can't be upgraded due to this.
But the code of the library is up-to-date with typescript and typedoc.
I've also published the new docs here:
https://www.maplibre.org/maplibre-gl-geocoder/
These can obviously be improved, but they are generated from the code itself mainly and not just the comments.

**Comment by HarelM** [comment]
P.S. I don't know what the debug folder is for, I would advise to delete it if no one know what it is used for either...

**Comment by HarelM** [comment]
This now migrated tests to jest and typescript.
It doesn't use the typescript file though and there's an error test I was not able to resolve, but otherwise this is now fully up to date with latest technologies.
I'll wait a day or two before I merge this.

**Comment by danawoodman** [comment]
nice! one thing i'd suggest is having a look at vitest which is mostly API compatible with Jest but much faster (built by same people who build Vite)

**Comment by HarelM** [comment]
In this project, which is very small, I prefer well documented battle tested framework over speed.
I've used a lot of frameworks, and jest excels in mocking capabilities, like no other.

**Review by thaddmt — APPROVED** [review]
Wow thanks for doing this, looks so much more modern now :)

**Pull request merged**
