### PR TITLE
Update CI

### PR DESCRIPTION
**Pull request by wipfli**
Updates the CI files to node version 16. Introduces a test workflow. Removes legacy travis config file.

 - [x] briefly describe the changes in this PR
 - [ ] write tests for all new functionality
 - [ ] run `npm run docs` and commit changes to API.md
 - [ ] update CHANGELOG.md with changes under `master` heading before merging

### CODE REVIEW

**Comment by Cactusbone** [comment]
Looks okay to me. However running against node 16 instead of node 10 might hide some problems, when the package.json only ask for node > 6.

Seeing as package-lock is already using version 2, I think updating node requirement in package.json as well would be nice :)  

Why did you update to node 16 here ? How about adding test workflow using node 10 here and updating in another PR ?

**Comment by wipfli** [comment]
Good question. I guess you are talking about this section:

https://github.com/maplibre/maplibre-gl-geocoder/blob/b0a3db7d52fdac1c03cbbdbc65ba437005bad5c9/package.json#L25-L27

IIRC, this is only used by node but since this plugin runs in a browser, we can remove it?

**Comment by wipfli** [comment]
I think there was some discussion about the node engine in GL JS...

**Comment by wipfli** [comment]
@HarelM

**Comment by Cactusbone** [comment]
> IIRC, this is only used by node but since this plugin runs in a browser, we can remove it?

Actually, I'm using it as a npm dependency and it's packaged using browserify (like prepublish step).

Keeping it allows some tools (like nodist on windows) to pick an appropriate node to run commands. However this package does not seems to have any :) 

Looks okay to me to update to node 16 to build and test. You may lose node 6 compatibility without noticing, but that was already the case since you were test using node 12. (ie if you start using const/let instead of var). This should be handled by browserify though...

**Review by HarelM — APPROVED** [review]

**Pull request merged**
