### PR TITLE
Create dependabot.yml

### PR DESCRIPTION
**Pull request by wipfli**
- [ ] briefly describe the changes in this PR
 - [ ] write tests for all new functionality
 - [ ] run `npm run docs` and commit changes to API.md
 - [ ] update CHANGELOG.md with changes under `master` heading before merging

### CODE REVIEW

**Comment by wipfli** [comment]
This repo has many security updates which dependabot can make. @HarelM

**Review by HarelM — APPROVED** [review]

**Comment by HarelM** [comment]
Daily?

**Comment by wipfli** [comment]
Monthly is better

**Comment by wipfli** [comment]
#51

**Pull request merged**
