### PR TITLE
chore: prep v1.4.0

### PR DESCRIPTION
**Pull request by thaddmt**
- [ ] briefly describe the changes in this PR
 - [ ] write tests for all new functionality
 - [ ] run `npm run docs` and commit changes to API.md
 - [ ] update CHANGELOG.md with changes under `main` heading before merging

### CODE REVIEW

**Review by slaymance — APPROVED** [review]
LGTM! Pulled down and verified tests pass with maplibre-gl bumped to v2 in `devDependencies`.

**Review by wipfli — COMMENTED** [review]
Cool looks good to me.

**Comment by wipfli** [comment]
Are you using MapLibre GL JS v2 at AWS now, @thaddmt?

**Comment by thaddmt** [comment]
@wipfli Yep we're workign on migrating everything over right now :)

**Comment by wipfli** [comment]
Beautiful

**Pull request merged**
